language: cpp
dist: xenial

compiler:
  - gcc

cache: apt

install:
  - sudo apt-get install pkg-config libglew-dev libcurl3-openssl-dev libjpeg-dev libxinerama-dev libxft-dev libsdl2-dev libsdl2-image-dev libfreetype6-dev libopus-dev libopusfile-dev gcc

before_script:
  - mkdir openspades.mk
  - cd openspades.mk

script:
  - cmake -DOPENSPADES_RESOURCES=off ..
  - cat CMakeCache.txt
  - make -k